version: '3.9'

services:
  redis:
    image: redis:7-alpine
    platform: linux/arm64
    ports:
      - "6379:6379"
    networks:
      - redis-network
  wire:
    build:
      context: tools/di
      dockerfile: Dockerfile
    working_dir: /worker
    volumes:
      - .:/worker
    command: ["/worker/tools/di/entrypoint.sh"]
networks:
  redis-network:
    driver: bridge
