// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/HMasataka/config"
	"github.com/HMasataka/ranking-maker/application/usecase"
	"github.com/HMasataka/ranking-maker/domain/service"
	"github.com/HMasataka/ranking-maker/infrastructure"
	"github.com/HMasataka/ranking-maker/infrastructure/persistence"
	"github.com/HMasataka/transactor/redis"
)

// Injectors from aggregate.wire.go:

func InitializeAggregateUseCase(cfg *config.RedisConfig) usecase.AggregateUseCase {
	client := infrastructure.NewRedisClient(cfg)
	connectionProvider := redis.NewConnectionProvider(client)
	transactor := redis.NewTransactor(connectionProvider)
	clientProvider := redis.NewClientProvider(connectionProvider)
	scoreRepository := persistence.NewScoreRepository(clientProvider)
	scoreService := service.NewScoreService(connectionProvider, scoreRepository)
	rankRepository := persistence.NewRankRepository(clientProvider)
	rankService := service.NewRankService(connectionProvider, rankRepository)
	queueRepository := persistence.NewQueueRepository(clientProvider)
	queueService := service.NewQueueService(connectionProvider, queueRepository)
	aggregateUseCase := usecase.NewAggregateUseCase(transactor, scoreService, rankService, queueService)
	return aggregateUseCase
}
